### ISSUE TITLE
Course project action should use notifications instead of dialogs

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#249]
From Intellij SDK docs:
> One of the leading design principles is avoiding the use of modal message boxes for notifying the user about errors and other situations that may warrant the user’s attention. As a replacement, the IntelliJ Platform provides multiple non-modal notification UI options.

* [ ] **check the consistency of the notification `type`s as well**

**Comment by OlliKiljunen** [comment]
How to: Test different notifications of `CourseProjectAction`:
+ network errors: disable internet connection 1) before firing action, 2) before clicking OK in dialog.
+ malformed course config file: either change course configuration file to be malformed or change code (e.g. make it read property "foo" instead of "modules")
+ local course file error `touch .idea/a-plus-project.json && chmod 000 .idea/a-plus-project.json`
