### ISSUE TITLE
Show points for each submission

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#302]
At the moment, points are only shown for the exercise as a whole. It would be useful to see how many points each submission got. However, this requires making a separate API request for each submission, which is pointless for most submissions since a student is likely to only be interested in the submissions of a few exercises during a single "work session". A relatively easy solution for this is generating the submission nodes of the exercises tree lazily. That is, the submission data for an exercise is only fetched if the exercise node in the tree is expanded.

**Comment by superseacat** [comment]
do you think it would become easier, if we ask A+ to create an endpoint to list only the results of the submissions (or extend one of the existing ones)? @Mankro

**Comment by superseacat** [comment]
also, based on, add the icon to the "Submissions" ( `AllIcons.Ide.External_link_arrow` )

https://apluslms.slack.com/archives/CSDV9CA31/p1596797531006800

**Comment by Mankro** [comment]
So, would you want to receive the points for all submissions in all exercises in the course for one student OR only all submissions in one exercise? We were previously talking about the former, but the issue description sounds like the latter.

@raphendyr was concerned that if the A+ points cache does not include points for all submissions (but only the best ones), it would be too heavy to query points for all submissions. However, it seems that the cache actually already contains points for all submissions: https://github.com/apluslms/a-plus/blob/9e595a0a902d19bcadeeaff8b3160873b0265f43/exercise/cache/points.py#L98

If the cache already contains the necessary data, we (that is @HenrikSundell) could try to implement a new A+ API endpoint. However, time is running short. @nikke234 could you provide an example of the API output you would need? We could consider extending the current `exercise/ID/points/me` endpoint so that it would provide points for all submissions if some extra parameter is enabled.

**Comment by Mankro** [comment]
nikke234's response copied from elsewhere:

The issue that you commented on is mostly related to UI stuff, but the API is helpful there, hence the confusion between points for all submissions vs points for submissions in a single exercise.
The need is specifically points of *all* submissions for *all* exercises (for a single user in a single course).

If it gets added to the `courses/<course-id>/points/me/` end point, then simply changing the submissions array from

```
"submissions": [
  "https://plus.cs.aalto.fi/api/v2/submissions/123/",
  "https://plus.cs.aalto.fi/api/v2/submissions/456/"
]
```

to

```
"submissions": [
  {
    "url": "https://plus.cs.aalto.fi/api/v2/submissions/123/",
    "points": 10
  },
  {
    "url": "https://plus.cs.aalto.fi/api/v2/submissions/456/",
    "points": 5
  }
]
```

would be enough for our needs

**Comment by raphendyr** [comment]
Sadly, change like that is not backwards compatible, thus it has to be done differently.

**Comment by nikke234** [comment]
> Sadly, change like that is not backwards compatible, thus it has to be done differently.

@raphendyr Markku mentioned that the points would get added if a paremeter is included in the request, so it would be backwards compatible in that case?

**Comment by raphendyr** [comment]
The key should change, so the data type of existing response doesn't change. E.g. by adding another key `submissions_and_points` or such. Alternatively, different end point can be used (again, it would be a new key in a sense).

Also, the data would be in `grade` as apparently that is the key in submission details page.

**Comment by superseacat** [comment]
> The key should change, so the data type of existing response doesn't change. E.g. by adding another key `submissions_and_points` or such. Alternatively, different end point can be used (again, it would be a new key in a sense).
> 
> Also, the data would be in `grade` as apparently that is the key in submission details page.

any estimate on this feature? @raphendyr

**Comment by Mankro** [comment]
I would let Henrik work on the issue, but he is working on another complex task at the moment.
