### ISSUE TITLE
issues with auto-complete in REPL

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#375]
#### Describe the bug
Members get properly imported, and work, the function name is used, however, the auto-complete does not work.

For example, for **Subprogmrams** module (o1 auto-imported by the plugin), the function `o1.play` works (as has a shortcut reference via the extended object), whereas the function `average` works as well, but does not show in auto-complete.

Overall seems like an issue with REPLs internal functionality.

#### To Reproduce
1. Start a REPL for **SubProgramms** module
2. type `o1.play` (auto-complete works)
3. start typing `o1.avera...` (no auto-complete)
4. type `o1.average` and hit "send" - REPL complains about the function lacking parameters

#### Expected behavior
Auto-completes in p. 3

#### Screenshots
![Screenshot from 2020-09-04 11:03:08](https://user-images.githubusercontent.com/9991098/92215939-3cc4df00-ee9e-11ea-80d5-4fcff81b1e48.png)

![Screenshot from 2020-09-04 11:02:53](https://user-images.githubusercontent.com/9991098/92215943-3d5d7580-ee9e-11ea-9bd2-dee713b07003.png)

![Screenshot from 2020-09-04 11:02:38](https://user-images.githubusercontent.com/9991098/92215945-3df60c00-ee9e-11ea-917c-ff778f43f0c0.png)

@jsorva is it something, that you've encountered already, by any chance?

**Comment by jsorva** [comment]
Yes, I’ve seen similar things. My not-terribly-well-informed current understanding is that the IJ Scala plugin’s REPL’s auto-complete (and red-color-warning) are limited in how they handle Scala’s package objects and/or type aliases. I haven’t looked into it deeply. In any case, since we’re looking to transition to Scala 3.0 (which discards package objects as a concept), perhaps this can remain as a low-priority issue. Good to be aware of it though.

**Comment by superseacat** [comment]
does not seem like something the plugin team needs to handle, so made an issue out of it just in case: https://youtrack.jetbrains.com/issue/SCL-18125

**Comment by nikke234** [comment]
Closing this for now, as we have reported the issue to JetBrains and it should hopefully go away with 3.0 anyways.
