### ISSUE TITLE
Add module export functionality

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#404]
The text adventure assignment of O1 requires the student to somehow export their module to a single ZIP-file that they submit to A+. The ZIP-files are then imported and used by the teaching assistants that grade the assignment. Therefore, the ZIP-file should have a format that is convenient to import into IntelliJ. The obvious answer of creating a ZIP of the module directory doesn't always work, as the text adventure module of the student may have dependencies on other modules. Creating a ZIP of the entire project is also an overkill. The plugin should have a feature that enables the student to create a ZIP of a module that also contains all the dependencies of that module.

**Comment by jsorva** [comment]
I expect that this will be useful in the future also in other courses which include manually graded assignments, such as @oseppala's Studio 1.

**Comment by OlliKiljunen** [comment]
I assume student's create the module via File -> New -> Module... -> Scala -> Scala and declare the dependency to O1Library via File -> Project Structure... -> Modules -> [Module name] -> Dependencies -> + -> Module Dependency...

This automatically creates an appropriate IML file inside the module dir. Just leaving that into ZIP should make it easy for TAs to import in their own IDEs (where O1Library is already there).

**Comment by OlliKiljunen** [comment]
Do you think it would be enough to add a wrapper/decorator for `FileFinder` that, in case the filename is of pattern "<something>.zip" and it doesn't exist per se, but file/dir named "<something>" exists, that is zipped (to a temp dir) and the path to the zip is returned?

**Comment by nikke234** [comment]
> I assume student's create the module via File -> New -> Module... -> Scala -> Scala and declare the dependency to O1Library via File -> Project Structure... -> Modules -> [Module name] -> Dependencies -> + -> Module Dependency...
> 
> This automatically creates an appropriate IML file inside the module dir. Just leaving that into ZIP should make it easy for TAs to import in their own IDEs (where O1Library is already there).

This solution works if the TA already has the dependency module, but it doesn't generalize to other dependencies than O1Library (or even O1Library that the student has modified in some way for the text adventure).

**Comment by nikke234** [comment]
> Do you think it would be enough to add a wrapper/decorator for `FileFinder` that, in case the filename is of pattern "something.zip" and it doesn't exist per se, but file/dir named "something" exists, that is zipped (to a temp dir) and the path to the zip is returned?

Do you mean for submitting the ZIP? I wasn't intending for the export functionality to be tied to submitting the assignment, but instead just creating a ZIP that the student can submit manually. Now that I think about it, your suggestion would be nice from the user experience point of view, but with the current assignment configuration the API doesn't return any filename for the assignment, so the `*.zip` solution won't work, and it is a bit of a hacky special case anyways.

**Comment by nikke234** [comment]
I wonder whether library dependencies should be included or not?

**Comment by OlliKiljunen** [comment]
Module-libraries (such as akka-actor for O1Lib) for sure but I think you're referring to external libraries. So:

With module dependencies, is the strategy here to traverse the whole dependency graph and include all the dependencies in the zip (with the module in question)? If so, I think it would make sense to include libraries too (I'd say only project-level libraries, though).

But I'm a bit suspicious is this really what we want here? For me, it would make perfect sense that the submission is required to be a single module with no other external dependencies than (unmodified) O1Library and scala-sdk-2.13.1.

After all, I think a _module_ is something with explicitly specified dependencies and interfaces. So, when a student is asked to implement a module, the assignment should specify what are its dependencies to other modules / external libraries. If a student is asked to implement a whole application (consisting of multiple modules and external libraries, whose structure the students have designed themselves), then it would make more sense that they created a whole new project for them, and zipped that, instead of implementing it as a part of the course project. (They could use plugin to import O1Library there too, if they wanted to have it).

**Comment by nikke234** [comment]
The assignment is open-ended in some ways so I don't know if we can require no other dependencies than unmodified O1Library and Scala SDK, any opinions @jsorva?

If we don't want to limit what dependencies the students use, then creating a new project would probably be the way to go, although there isn't really a difference between zipping a module and it's dependencies or zipping a separate project created for the assignment.

**Comment by jsorva** [comment]
In O1, we can require that if there are additional dependencies, the students does the zip manually. More generally, it could be nice to allow other dependencies, but that's in no way urgent.

**Comment by nikke234** [comment]
Alright, in that case just zipping the module by itself should be sufficient, which makes it really easy.
