### ISSUE TITLE
what it takes to start using Kotlin

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#455]
**do a poll and ensure at least the majority of the team + J agree on this!**

the idea here is to figure out what are the pros and cons of using Kotlin in our plugin development, and sketch a rough estimate on when this could be done, if ever

**Comment by nikke234** [comment]
I am strongly opposed to rewriting the existing Java code (unless it is being significantly changed for some other reason as well), but wouldn't mind using Kotlin in new code.

**Comment by superseacat** [comment]
> I am strongly opposed to rewriting the existing Java code (unless it is being significantly changed for some other reason as well), but wouldn't mind using Kotlin in new code.

if we significantly refactor some older feature, is it still acceptable?

**Comment by nikke234** [comment]
> > I am strongly opposed to rewriting the existing Java code (unless it is being significantly changed for some other reason as well), but wouldn't mind using Kotlin in new code.
> 
> if we significantly refactor some older feature, is it still acceptable?

Yeah sounds good, then it would make sense to rewrite :+1:

**Comment by superseacat** [comment]
| + | - |   
|---|---|
| hypier tech | no UI designer ([only a custom DSL](https://plugins.jetbrains.com/docs/intellij/kotlin.html#ui-in-kotlin)) |
| language of ~~love~~ android | need to learn new language |   
| full Java interop | more complex (3-lang) environment |
| more concise syntax |good support only via JB tools |
|| [some more](https://plugins.jetbrains.com/docs/intellij/kotlin.html#caution) plugin dev restrictions |

**Comment by OlliKiljunen** [comment]
Would the change imply any major changes in the overall architecture of our codebase? Kotlin is still a class-based OOP language, right? If the question is only about the syntax in which our classes are written, then it's pretty much the same for me, whether it's Java or Scala or Kotlin (or Smalltalk or PHP or C++ or whatever 😜).

95% of our code is just "getters and setters", so I don't expect the programming language having much effect on how our code gets structured, unless it's based on a different programming paradigm like JavaScript (no classes), C (no objects) or Lisp (((()))) would.

**Comment by jaakkonarhi** [comment]
I don't like java

**Comment by superseacat** [comment]
> I don't like java

this is more of a "would you like Kotlin better?" question 😉

**Comment by jaakkonarhi** [comment]
Kotlin seems much nicer to me

**Comment by nikke234** [comment]
I support switching to Kotlin, with the exception that I mentioned above.

**Comment by OlliKiljunen** [comment]
Perhaps this is out of the scope of this discussion, but how do you see we would start this injection of Kotlin? I can think of some options for new policies:
a) if a Java class is modified more than X lines, it should be rewritten in Kotlin
b) all new classes would be written in Kotlin, pre-existing classes stay in Java
c) only new components / modules / whatever larger entities will be written in Kotlin, otherwise stick with Java
d) other: ___________________

**Comment by nikke234** [comment]
My personal preference would be for option `b`. Option `a` sounds good as well, but I wouldn't put a hard line limit on it, instead just going with what "feels right". So there would be no rewrites just for the sake of writing it in Kotlin, but if it is pretty much getting completely revamped, then might as well write it in Kotlin.

BTW I don't think that's off topic here, since switching to Kotlin only makes sense if we have a clear plan of how to do it.

**Comment by superseacat** [comment]
> BTW I don't think that's off topic here, since switching to Kotlin only makes sense if we have a clear plan of how to do it.

this is more of a chicken-end-egg problem for me... we'll make the plan if we agree to move (I'd say not having a plan at this point is not crucial)

**Comment by superseacat** [comment]
@stellatsv @Taikelenn what do you think?

**Comment by stellatsv** [comment]
I support the decision to use Kotlin because I have been wanting to learn a new language and learning one on the job seems like a good opportunity. Other than that, I am not at all familiar with Kotlin (yet) so I cannot give a more structured technical argument.

**Comment by superseacat** [comment]
and how about Scala?

**Comment by stellatsv** [comment]
Final decision: use Kotlin for UI tests and keep the existing code in Java.
