### ISSUE TITLE
configuration of proper naming, contacts, logo, etc.

### ISSUE THREAD

**Issue by superseacat** [Aalto-LeTech/intellij-plugin#5]
* [x] add naming

**Comment by superseacat** [comment]
applied for an exchange email list "intellij-plugin-letech@aalto.fi" - we will register a new JB account with it. and optionally can list the email as a contact in plugin.xml (for contact purposes)

**Comment by superseacat** [comment]
@jsorva 
the proposed naming:
* name: Intellij IDEA plugin for A+
* vendor name: Learning + Technology Research Group
* vendor url: https://research.cs.aalto.fi/LeTech/
* vendor email (optional): intellij-plugin-letech@aalto.fi
* description, how the TMC has it: 
<i>
 TMC-IntelliJ is the IntelliJ IDEA plugin for University of Helsinki's TestMyCode framework.
    TestMyCode is used by various online programming courses for exercise testing and submitting.
    <p>
      Set your TMC settings in the TMC menu and you're ready to go!
    </p>
    <p>
      If you run into any bugs, please submit an issue of it
      at the Github repository.
    </p>
</i>

this will be displayed like this: https://plugins.jetbrains.com/plugin/8551-tmc-plugin-for-intellij

**Comment by jsorva** [comment]
Minor edit: capital J in IntelliJ

Description could be: 

_This plugin supports the educational use of IntelliJ (and its Scala plugin) in programming courses that rely on the A+ course platform, which has been developed at Aalto University. The plugin accesses programming assignments and automated grading services provided by A+ and otherwise enhances student experience._
