### ISSUE TITLE
Investigate "Assessable Within-IDE Activities"

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#501]
From requirements wiki:

> (This is a major new feature. It would be great to have; however, it is unclear at this point how complicated its implementation would be.)
> 
>     ☀☀☀☀ Enable support for "tutorial-like" activities within the IDE:
>         The assignment has a goal (e.g., "find the file and line of code where X is defined", "try method X in the REPL", "try method X in the REPL on various inputs and then answer this multiple-choice question about it", "start the debugger and step until line X", etc. etc.)
>             The goal can be IDE-related and/or programming-content-related.
>         While the assignment is "active", the plugin tracks whether the student has completed it. Once they have, the student automatically scores points in A+.
>         Ideally, hints and/or feedback on failed attempts could be provided, as configured by the teacher.

**Comment by superseacat** [comment]
@nikke234 investigates and presents

**Comment by nikke234** [comment]
Preliminary investigations suggest that this is doable, so I'm closing this now. I suggest that in tomorrows weekly we select some very simple assessable activity that we want to implement. Then we create issues for that simple activity and implement it. After that we can work on more activities.

I suggest that the following general design goals should be followed:

1. The implementation must work with the existing A+ API.
2. The implementation would very preferably not be O1 specific.
3. It would be nice if the implementation is language agnostic and doesn't have a dependency on the Scala plugin.

There are a million ways to implement it, but here is an outline of a possible implementation that meets the goals:

- The plugin keeps a queue of recent events (say, for an example, the last 50 events).
  - Due to multi-course support, this queue must in practice be project-specific.
- The course configuration defines a set of trigger events (as strings) and corresponding A+ exercises (IDs).
- When a trigger event is encountered and the student hasn't scored points from the corresponding exercise, a dialog is shown which allows the user to submit the activity queue to the exercise (and view the data that is going to be submitted).
- The plugin can send the activity queue as a simple string or some similar format. There are already graded oneliner assignments in O1, where input from a single line text field is graded, so grading the submission should be relatively easy.
  - Preventing students from manually sending HTTP requests with the correct contents is not important.
- Something for JS to consider: how are the exercises which these activities use presented in the course materials?

The list of activities that can be listened to is almost endless, but some significant ones are listed here:

- Filesystem events
- Editor events
- Document events
- Anything related to functionality that we implement
- Interactions with the REPL (but this one is not trivial!)

To more concretely estimate what can be done before O1 2021, it would be nice to get a specific "wish list" of assessable activities.

It should be noted that events could possibly fall under telemetric data, in which case the following must be kept in mind:
> In case of transfer of any statistics and/or telemetric data, the Plugin asks for explicit permission from the user.

**Comment by OlliKiljunen** [comment]
I think it would be important that after each (preferably small) step user would get some feedback (and possibly also guidance) even though, naturally, no data would be transferred to the server.

Like, the procedure could be: open the project tree -> open some file -> edit file.

There would then be a counter (0/3) showing how many steps are done. When a user opens the project tree it turns to 1/3 (plus notification?), then, when they open the file, to 2/3, and after editing it, to 3/3, and submission window opens.

**Comment by nikke234** [comment]
Yeah, very good point, and should be very doable if the configuration just stores a sequence of events instead of a single event
