### ISSUE TITLE
Replace text when no assignments to show

### ISSUE THREAD

**Issue by jaakkonarhi** [Aalto-LeTech/intellij-plugin#524]
![image](https://user-images.githubusercontent.com/34682147/107655542-4bed5b80-6c8c-11eb-861f-0083b3c352f9.png)

If all the assignments are filtered out this text shows. It could be replaced with something like "You've completed everything" or "No assignments to show" or a loading bar when loading them for the first time (#519)

**Comment by OlliKiljunen** [comment]
Similarly, when opening an existing A+ project, the modules list's message says the project should be turned to A+ project until indexing is done.

**Comment by stellatsv** [comment]
When the user is not authenticated the filtering options look like this:
![image](https://user-images.githubusercontent.com/51020697/110694176-f9528100-81f0-11eb-899b-8a3c2ce40418.png)

It would be better if the icons were disabled in that case since there are no available assignments to interact with.
