### ISSUE TITLE
Plugin doesn't handle submission status "waiting" in the A+ API

### ISSUE THREAD

**Issue by nikke234** [Aalto-LeTech/intellij-plugin#527]
The plugin only considers the following statuses: "unknown", "unofficial", and "graded". The plugin should also account for "waiting", which is the status of a submission that is currently in grading, as @jaakkonarhi discovered. `getStatusText` in `SubmissionResultViewModel` should return "in grading" instead of "0/n" when the status is "waiting".

**Comment by stellatsv** [comment]
Some remarks about the issue (from working on #364) that may help:
- In the `Exercise.java` method `fromJsonObject`(called when updating `mainViewModel`) the only available information is the number of submissions. The extra submissions are marked as Unofficial and the rest as Graded. This is not accurate because the last submission may be still In Grading. 

- Additionally, it is because the status Unknown is not set to any of the loaded SubmissionResults that the text 'In Grading' is not displayed.
