### ISSUE TITLE
Make overall plan for where we want to be wrt documentation at the end of 2021 and act accordingly

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#530]

**Comment by stellatsv** [comment]
Ideas so far:
- Manual for the course configuration
- Introduction to the plugin

**Comment by stellatsv** [comment]
Main Focus: future developers/maintainers

- [ ] Architecture: how/why we are using MVVM 
- [ ] Communication with A+ platform (submissions, etc.)
- [ ] Course configuration
- [ ] Gradle tasks that we use
- [ ] Setup: both from developers’ and users’ aspect
- [ ] Troubleshooting? Common-issues that come up with users? Perhaps use the existing document?
- [ ] Workflows: Some basic explanation of the plug-in's activities, this could also be reused if we make a user manual
- [ ] Principles that the team and the project adhere to during development
- [ ] Build and libraries/dependencies details – if there are reasons why we have selected one library over another or a specific version
- [ ] How we have set up GitHub Actions.
- [ ] We can select any other areas that are not too clear and something could be written about those

It could be placed in the Wiki and also have a link in the README.md so that potential open-source contributors can find it more easily.
