### ISSUE TITLE
Improved module updates

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#534]
~~safer updating without destroying students' work and/or~~ possibility to mark an update as "minor" so that people who have modified their copy of the module do not get an update notification

**Comment by jaakkonarhi** [comment]
idea: set the "id" property as "major.minor", if no dot found then it works as before. Also additional "changelog" property would be nice, the value of which would be set as the tooltip in the modules list if an update is available, since now the ids are kind of used as changelogs (like "b-fix-method-name")
