### ISSUE TITLE
IDE act: Design the UI workflow

### ISSUE THREAD

**Issue by OlliKiljunen** [Aalto-LeTech/intellij-plugin#561]
Make a paper prototype (?)

**Comment by jaakkonarhi** [comment]
![Screenshot from 2021-02-27 15-36-38](https://user-images.githubusercontent.com/34682147/109390156-8b68a880-7918-11eb-9aef-a2d83340d2de.png)
This is what the assignment could look like. I think the submit icon should change, since you're not submitting anything yet

![image3791](https://user-images.githubusercontent.com/34682147/109390172-a76c4a00-7918-11eb-9f83-b2b7034fd781.png)
More text can be added here

![image3792](https://user-images.githubusercontent.com/34682147/109390180-b81cc000-7918-11eb-83f6-f37c29b54b8f.png)
The relevant section could be highlighted. Clicking the progress button in the top right corner could open a help window or some tips

![image4898](https://user-images.githubusercontent.com/34682147/109390187-c36feb80-7918-11eb-9f6c-26c16889ecc7.png)
The next step could start as soon as you finish the last one
